wallpaper {
    monitor = 
    path = ~/.config/dotfiles/wallpapers/current.jpg
    fit_mode = cover
}

splash = false

# preload = ~/.config/dotfiles/wallpapers/current.jpg
# wallpaper = , ~/.config/dotfiles/wallpapers/current.jpg
